### PR TITLE
Use pre-releases for gz-sim8 to test gz-transport 13.2.0

### PR DESCRIPTION
**Pull request by iche033**

### CODE REVIEW

**Comment by j-rivero** [comment]
Out of curiosity and for future developments: what is the use case that requires to modify the yaml file here? To get green CI on Jenkins? To test a `-ci-pr_any-` manual build? Other?

**Review by j-rivero — APPROVED** [review]

**Comment by iche033** [comment]
after this PR is merged, my use case is to trigger a build in https://build.osrfoundation.org/job/gz_sim-ci-gz-sim8-jammy-amd64/ (which has started failing recently) to see we can get green CI back on Jenkins.

**Comment by j-rivero** [comment]
> after this PR is merged, my use case is to trigger a build in https://build.osrfoundation.org/job/gz_sim-ci-gz-sim8-jammy-amd64/ (which has started failing recently) to see we can get green CI back on Jenkins.

I see. My point here is what we need to modify to avoid setting this permanent change and allow this kind of change. My initial thought was to add a `REPOS_TO_USE` to https://build.osrfoundation.org/job/gz_sim-ci-pr_any-jammy-amd64 but that will change all packages to use the prerelease repository.

We can add a GZDEV_BRANCH to the `-ci-pr_any-` jobs so you can modify this repository in a branch and test a job directly from there without modifying the permanent configuration of all jobs.

**Comment by iche033** [comment]
> We can add a GZDEV_BRANCH to the -ci-pr_any- jobs so you can modify this repository in a branch and test a job directly from there without modifying the permanent configuration of all jobs.

yep that sounds like a good idea to avoid changing and reverting changes in this file after testing.

**Pull request merged**
